spring.application.name=hospital
spring.datasource.url=jdbc:mysql://localhost:3306/sghbcxp
spring.datasource.username=root
spring.datasource.password=marcelo81
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true