version: "3.8"
services:
  backend:
    build: ./backend
    container_name: sghbc-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:sghbcxp"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"

  frontend:
    build: ./frontend
    container_name: sghbc-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: "http://backend:8080"
